vse: &vse
  docker:
    - image: circleci/node:8.11.3

ansible:
  docker: &ansible
    - image: 'circleci/python:latest'
      environment:
        ANSIBLE_HOST_KEY_CHECKING: no
        AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
        AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
        AWS_SESSION_TOKEN: $AWS_SESSION_TOKEN

version: 2.1
orbs:
  ansible-playbook: orbss/ansible-playbook@0.0.5

jobs:
  build:
    <<: *vse
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    docker: *ansible
    steps:
      - attach_workspace:
          at: .
      - ansible-playbook/install
      - run:
          command:
            sudo pip install ansible boto boto3
      - add_ssh_keys:
          fingerprints:
            - "cc:ca:5b:72:76:54:b9:e0:47:17:76:d9:01:45:0e:92"
      - run: echo $SSH_PRIVATE_KEY | sed 's/|/\n/g' > devops-final-hw.pem
      - run: chmod 400 devops-final-hw.pem
      - ansible-playbook/playbook:
          playbook: ./ansible/ec2_deploy.yml
          playbook-options: --user ubuntu --key-file devops-final-hw.pem

workflows:
  version: 2.1
  build:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
